export const allCities = [
  "Agar",
  "Aldburg",
  "Almaida",
  "Alqualondë",
  "Andúnië",
  "Annúminas",
  "Archet",
  "Armenelos",
  "Avallónë",
  "Bablon",
  "Belegost",
  "Bree",
  "Breredon",
  "Brithombar",
  "Bucklebury",
  "Budgeford",
  "Bywater",
  "Calembel",
  "Caras Galadhon",
  "Carn Dûm",
  "Celbaros",
  "Combe",
  "Crickhollow",
  "Dale",
  "Deephallow",
  "Dol Amroth",
  "Dwaling",
  "Dáin's hall",
  "Edhellond",
  "Edoras",
  "Eglarest",
  "Elvenking's Halls",
  "Ephel Brandir",
  "Estirin",
  "Forgotten Villages",
  "Forlond",
  "Fornost Erain",
  "Framsburg",
  "Frogmorton",
  "Gamwich",
  "Goblin-town",
  "Gondolin",
  "Great Smials",
  "Greenholm",
  "Grey Havens",
  "Hardbottle",
  "Harlond (Gondor)",
  "Harlond (Lindon)",
  "Havens of Círdan",
  "Havens of the Falas",
  "Haysend",
  "Hobbiton",
  "Kingdom under the Mountain",
  "Kortirion",
  "Lake-town",
  "Linhir",
  "Little Delving",
  "Lond Daer",
  "Long Cleeve",
  "Longbottom",
  "Menegroth",
  "Michel Delving",
  "Minas Anor",
  "Minas Ithil",
  "Minas Morgul",
  "Minas Tirith",
  "Moria",
  "Mugworth",
  "Mundburg",
  "Nargothrond",
  "Needlehole",
  "Newbury",
  "Nindamos",
  "Ninwi",
  "Nobottle",
  "Nogrod",
  "Nulukkizdîn",
  "Oatbarton",
  "Ondosto",
  "Osgiliath",
  "Ost-in-Edhil",
  "Overhill",
  "Pelargir",
  "Pincup",
  "Quarry",
  "Rivendell",
  "Rushey",
  "Rómenna",
  "Rûm",
  "Scary",
  "Staddle",
  "Standelf",
  "Stock",
  "Taruithorn",
  "Tavrobel",
  "Tharbad",
  "Tighfield",
  "Tirion",
  "Tookbank",
  "Trui",
  "Tuckborough",
  "Udul",
  "Umbar",
  "Underharrow",
  "Underhill",
  "Undertowers",
  "Upbourn",
  "Valmar",
  "Vinyalondë",
  "Vinyamar",
  "Waymeet",
  "Whitfurrows",
  "Whitwell",
  "Willowbottom",
  "Woodhall",
];

export function isValidCity(target:string) {
  let left = 0;
  let right = allCities.length - 1;
  target=target.toLowerCase();
  while (left <= right) {
    const mid = Math.floor((left + right) / 2);
    const midValue = allCities[mid].toLowerCase();
    if (midValue==target) {
      return true;
    } else if (midValue < target) {
      left = mid + 1;
    } else {
      right = mid - 1;
    }
  }
  return false;
}